sudo: required
dist: xenial
language: python
cache: pip
matrix:
  include:
  - python: 3.7
    env: NOX_SESSION=check
  - python: 3.7
    env: NOX_SESSION=docs
  - python: 3.6
    env: NOX_SESSION=test-3.6
  - python: 3.7
    env: NOX_SESSION=test-3.7
  - python: 3.8-dev
    env: NOX_SESSION=test-3.8
install:
- pip install --upgrade nox
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
